
package AuctionWS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Registration", targetNamespace = "http://web.auction/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Registration {


    /**
     * 
     * @param arg0
     * @return
     *     returns AuctionWS.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerUser", targetNamespace = "http://web.auction/", className = "AuctionWS.RegisterUser")
    @ResponseWrapper(localName = "registerUserResponse", targetNamespace = "http://web.auction/", className = "AuctionWS.RegisterUserResponse")
    @Action(input = "http://web.auction/Registration/registerUserRequest", output = "http://web.auction/Registration/registerUserResponse")
    public User registerUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns AuctionWS.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://web.auction/", className = "AuctionWS.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://web.auction/", className = "AuctionWS.GetUserResponse")
    @Action(input = "http://web.auction/Registration/getUserRequest", output = "http://web.auction/Registration/getUserResponse")
    public User getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
